game/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from rest_framework.generics import *
from game.models import *
from game.views import *

urlpatterns = patterns('game.views',
    url(r'^$', 'home', name='home'),

    url(r'^game/$', 'game', name='game'),

    url(r'^create-account/$', 'create_account', name='create-account'),

    url(r'^how-to-play/$', 'how_to_play', name='how-to-play'),

    url(r'^leaderboards/$', 'leaderboards', name='leaderboards'),

    #url(r'^profile/$', 'profile', name='profile'),
    #url(r'^profile/(?P<account_id>\d+)/$', 'profile', name='profile'),

    url(r'^api/action/(?P<action>rest|walk|run|north|south|east|west)/$', 'api_action', name='api-action'),
    url(r'^api/cancel/(?P<move_position>\d+)/$', 'api_cancel', name='api-cancel'),

    url(r'^api/initial-load/$', 'api_initial_load', name='api-initial-load'),
    url(r'^api/update-chat/$', 'api_update_chat', name='api-update-chat'),

)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse
from django.conf import settings
from django.views.generic import TemplateView

#from library.forms import *

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    url(r'', include('game.urls')),

    url(r'^qunit-tests/', TemplateView.as_view(template_name='qunit-tests.html'), name='qunit-tests'),
    url(r'^login/$', 'django.contrib.auth.views.login', {
        'template_name': 'login.html',
    }, 'login'),

    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^password-change/$', 'django.contrib.auth.views.password_change', {
        'template_name': 'password_change.html',
    }, 'password_change'),

    url(r'^password-reset/$', 'django.contrib.auth.views.password_reset', {
        'template_name': 'password_change.html',
    }, 'password_reset'),

    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', name='logout'),

    url(r'', include('django.contrib.auth.urls')),

)

if settings.DEBUG:
    urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

game/models.py
from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import *
from game.models import *
from util.functions import *
import math
import ipdb

class Account(AbstractBaseUser, PermissionsMixin):
    TEAMS = (
        ('red', 'Red'),
        ('blue', 'Blue'),
    )
    DIRECTIONS = (
        ('north', 'North'),
        ('south', 'South'),
        ('east', 'East'),
        ('west', 'West'),
    )
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(blank=True)
    team = models.CharField(max_length=5, choices=TEAMS, blank=True)
    has_flag = models.BooleanField(default=False)
    col = models.IntegerField(null=True, blank=True)
    row = models.IntegerField(null=True, blank=True)
    last_col = models.IntegerField(null=True, blank=True)
    last_row = models.IntegerField(null=True, blank=True)
    last_direction = models.CharField(max_length=10, choices=DIRECTIONS, blank=True, default='south')
    direction = models.CharField(max_length=10, choices=DIRECTIONS, blank=True, default='south')
    last_chat_message = models.CharField(max_length=75, blank=True, default='')
    chat_message = models.CharField(max_length=75, blank=True, default='')
    inactive_turns = models.IntegerField(default=0)

    flags_gotten = models.IntegerField(default=0)
    enemies_tagged = models.IntegerField(default=0)

    actions = models.CharField(max_length=255, default='', blank=True)
    last_actions = models.CharField(max_length=255, default='', blank=True)
    stamina = models.IntegerField(default=10)


    is_staff = models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.')
    is_active = models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.')

    date_joined = models.DateTimeField(default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = 'account'
        verbose_name_plural = 'accounts'

    def __unicode__(self):
        return self.username

    def get_username(self):
        return self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return self.username

    def email_user(self, subject, message, from_email=None):
        send_mail(subject, message, from_email, [self.email])

ACTIONS = [
    { 'which': 'rest', 'name': 'Rest', 'seconds': 1, 'stamina': 1, 'icon': 'glyphicon-pause' },
    { 'which': 'walk', 'name': 'Walk', 'seconds': 2, 'stamina': 0, 'icon': 'glyphicon-step-forward' },
    { 'which': 'run', 'name': 'Run', 'seconds': 1, 'stamina': -2, 'icon': 'glyphicon-fast-forward' },
    { 'which': 'north', 'name': 'Face North', 'seconds': 1, 'stamina': 0, 'icon': 'glyphicon-chevron-up' },
    { 'which': 'south', 'name': 'Face South', 'seconds': 1, 'stamina': 0, 'icon': 'glyphicon-chevron-down' },
    { 'which': 'east', 'name': 'Face East', 'seconds': 1, 'stamina': 0, 'icon': 'glyphicon-chevron-right' },
    { 'which': 'west', 'name': 'Face West', 'seconds': 1, 'stamina': 0, 'icon': 'glyphicon-chevron-left' },
]
def get_action_by_name(which):
    for action in ACTIONS:
        if action['which'] == which:
            return action


TILES = [
    None,
    'grass', 'water', 'corn', 'rocks', 'trees', None, None, None, None, None,
    'dirt', 'shrubbery', 'grass', 'grass', None, None, None, None, None, None,
    'road', 'road', 'red-flag', 'blue-flag', None, None, None, None, None, None,
    'road', 'road', 'water', 'water', None, None, None, None, None, None,
    'road', 'road', 'water', 'water', None, None, None, None, None, None,
    'road', 'road', None, None, None, None, None, None, None, None,
    'road', 'road', None, None, None, None, None, None, None, None,
    'road', 'road', None, None, None, None, None, None, None, None,
    'road', 'road', None, None, None, None, None, None, None, None,
    None, None, None, None, None, None, None, None, None, None,

]

#class SquareOccupiedException(Exception):
#    pass
#class InvalidPlacementException(Exception):
#    pass
#class SquareDoesNotExistException(Exception):
#    pass




#class ObjectManager(models.Manager):
#    def method(self):
#        pass

RED_START = { 'col': 14, 'row': 14 }
BLUE_START = { 'col': 36, 'row': 61 }

    

class Square(models.Model):
    TERRAIN_TYPES = (
        ('grass', 'grass'),
        ('dirt', 'dirt'),
        ('water', 'water'),
        ('corn', 'corn'),
        ('tree', 'tree'),
        ('rock', 'rock'),
        ('building', 'building'),
        ('shrubbery', 'shrubbery'),
        ('road', 'road'),
    )
    col = models.IntegerField()
    row = models.IntegerField()
    terrain_type = models.CharField(max_length=10, choices=TERRAIN_TYPES)
    tile = models.IntegerField()

    def get_css_offset_x(self):

        return str(32 * (self.tile-1) % 320 * -1) + 'px'
    def get_css_offset_y(self):
        return str(32 * (self.tile-1) / 320 * 32 * -1) + 'px'

    def get_terrain_type(self):
        return TILES[self.tile]

class Log(models.Model):
    TEAMS = (
        ('red', 'Red'),
        ('blue', 'Blue'),
    )
    col = models.IntegerField()
    row = models.IntegerField()
    team = models.CharField(max_length=5, choices=TEAMS)
    has_flag = models.BooleanField(default=False)


class Announcement(models.Model):
    text = models.CharField(max_length=75)

game/forms.py
from django import forms
from game.models import *

class CreateAccountForm(forms.ModelForm):
    error_messages = {
        'username_taken': "That username is taken.",
        'password_mismatch': "Passwords do not match",
    }
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repeat password", widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ("username",)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def save(self, commit=True):
        account = super(CreateAccountForm, self).save(commit=False)
        account.set_password(self.cleaned_data["password1"])
        if commit:
            account.save()
        return account

game/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import F
from django.contrib import messages 
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import *
from django.shortcuts import _get_queryset
from game.models import *
from game.serializers import *
from game.forms import *
from util.functions import *
from django.contrib.auth import authenticate, login
from django.db.models import Count, Min, Sum, Avg

from rest_framework.generics import *
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated

import settings

from django.utils import simplejson
import random
import math
import ipdb

import datetime

def home(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('game'))
    return render(request, 'home.html', locals())

def how_to_play(request):
    return render(request, 'how-to-play.html', locals())

def leaderboards(request):
    top_taggers = Account.objects.order_by('-enemies_tagged')[:20]
    top_flag_getters = Account.objects.order_by('-flags_gotten')[:20]

    red_flags = Account.objects.filter(team='red').aggregate(red_flags=Sum('flags_gotten'))['red_flags']
    blue_flags = Account.objects.filter(team='blue').aggregate(blue_flags=Sum('flags_gotten'))['blue_flags']

    red_tags = Account.objects.filter(team='red').aggregate(red_tags=Sum('enemies_tagged'))['red_tags']
    blue_tags = Account.objects.filter(team='blue').aggregate(blue_tags=Sum('enemies_tagged'))['blue_tags']

    return render(request, 'leaderboards.html', locals())

def create_account(request):
    if request.method == 'POST':
        form = CreateAccountForm(request.POST)
        if form.is_valid():
            form.save()
            account = authenticate(username=request.POST['username'],
                                    password=request.POST['password1'])
            account.team = random.choice(['red', 'blue'])
            if account.team == 'red':
                account.col = RED_START['col']
                account.row = RED_START['row']
            else:
                account.col = BLUE_START['col']
                account.row = BLUE_START['row']

            account.last_col = account.col
            account.last_row = account.row
            account.save()
            login(request, account)

            #send_templated_mail(
            #    template_name='registration-confirmation',
            #    from_email=settings.ADMIN_EMAIL_SENDER,
            #    recipient_list=[account.email],
            #    context={
            #        'domain': settings.SITE_DOMAIN,
            #        'account': account,
            #    })
            return HttpResponseRedirect(reverse('how-to-play'))
    else:
        form = CreateAccountForm()
    return render(request, 'create-account.html', locals())

@login_required
def game(request):
    rows = []
    col_span = 10
    row_span = 8

    # If the player hasn't moved in a while, reset them back to the beginning
    if request.user.inactive_turns >= settings.TURNS_TILL_DEACTIVATION:
        request.user.inactive_turns = 0
        if request.user.team == 'red':
            request.user.col = RED_START['col']
            request.user.row = RED_START['row']
        if request.user.team == 'blue':
            request.user.col = BLUE_START['col']
            request.user.row = BLUE_START['row']
        request.user.stamina = 10
        request.user.save()

    announcements = Announcement.objects.all()

    for row in range(request.user.row-row_span, request.user.row+row_span+1):
        squares = (Square.objects.
            filter(col__gte=request.user.col-col_span).
            filter(col__lte=request.user.col+col_span).
            filter(row=row).
            order_by('col'))
        rows.append(squares)

    return render(request, 'game.html', locals())

class AccountAPIView(RetrieveAPIView, ListAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = AccountSerializer
    model = Account

@login_required
@api_view(['GET'])
def api_username_existence(request, username):
    taken = (get_object_or_None(Account, username=username) != None)
    return Response({ 'taken': taken })

@login_required
@api_view(['GET'])
def api_email_existence(request, email):
    taken = (get_object_or_None(Account, email=email) != None)
    return Response({ 'taken': taken })

@login_required
@api_view(['POST'])
def api_action(request, action):
    if request.user.actions == '':
        current_actions = []
    else:
        current_actions = request.user.actions.split(',')

    total_seconds = 0
    prev_actions_stamina = 0
    for current_action in current_actions:
        this_action = get_action_by_name(current_action)
        total_seconds += this_action['seconds']
        prev_actions_stamina += this_action['stamina']

    if total_seconds + get_action_by_name(action)['seconds'] > 10:
        return Response({
            'error': 'You do not have enough seconds to add that action.'
        }, status=status.HTTP_400_BAD_REQUEST)

    if request.user.stamina + prev_actions_stamina + get_action_by_name(action)['stamina'] < 0:
        return Response({
            'error': 'You do not have enough stamina to add that action.'
        }, status=status.HTTP_400_BAD_REQUEST)

    current_actions.append(action)
    request.user.actions = ','.join(current_actions)

    request.user.save()

    return Response('')

@login_required
@api_view(['POST'])
def api_cancel(request, move_position):
    move_position = int(move_position)
    current_actions = request.user.actions.split(',')

    if current_actions != '' and (move_position < 0 or move_position >= len(current_actions)):
        return Response({
            'error': 'Invalid cancel.'
        }, status=status.HTTP_400_BAD_REQUEST)

    current_actions = current_actions[:move_position] # Delete all moves after this one also
    request.user.actions = ','.join(current_actions)
    request.user.save()

    return Response('')

@login_required
@api_view(['POST'])
def api_update_chat(request):
    request.user.chat_message = request.DATA['message']
    request.user.save()

    return Response('')

@login_required
@api_view(['GET'])
def api_initial_load(request):

    col_span = 10
    row_span = 8
    other_players = (
        Account.objects.
            filter(inactive_turns__lt=settings.TURNS_TILL_DEACTIVATION).
            filter(col__gte=request.user.col-col_span).
            filter(col__lte=request.user.col+col_span).
            filter(row__gte=request.user.row-row_span).
            filter(row__lte=request.user.row+row_span).
            exclude(pk=request.user.id)
    )

    return Response({
        'seconds_remaining': 30 - datetime.datetime.now().second % 30,
        'action_data': ACTIONS,
        'user_actions': request.user.actions,
        'account': AccountSerializer(request.user).data,
        'other_players': AccountSerializer(other_players, many=True).data,
    })

templates/base.html
{% load custom_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Ludum Dare 27: The Game</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="The official Ludum Dare entry of David S. Colgan">
    <meta name="author" content="David S. Colgan">

    <link rel="shortcut icon" href="{{ STATIC_URL }}images/favicon.ico">

    <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>

    {% block head %}{% endblock %}

    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/style.css?v={% setting "VERSION" %}">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css">
</head>
<body class="{% block body_class %}{% endblock %}">

    <div class="navbar navbar-default">
        <div class="container-fixed">
        {% if request.user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'game' %}">Capture the Massively<br/>Multiplayer Online Flag&nbsp;</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'home' %}">Capture the Massively<br/>Multiplayer Online Flag&nbsp;</a>
        {% endif %}
        <ul class="nav navbar-nav">
            <li><a href="{% url 'game' %}">Game</a></li>
            <li><a href="{% url 'how-to-play' %}">How To Play</a></li>
            <li><a href="{% url 'leaderboards' %}">Leaderboards</a></li>
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
        </ul>
        {% block game_toolbar %}{% endblock %}
        </div>
    </div>

    {% block content %}{% endblock %}

    <script src='{{ STATIC_URL }}js/jquery-2.0.1.min.js'></script>
    <script src='{{ STATIC_URL }}/js/jquery.cookie.js'></script>
    <script src='{{ STATIC_URL }}js/lodash.js'></script>
    <script src='{{ STATIC_URL }}bootstrap/js/bootstrap.js'></script>
    <script src='{{ STATIC_URL }}js/knockout-2.3.0.js'></script>
    <script src='{{ STATIC_URL }}js/all-pages.js?v={% setting "VERSION" %}'></script>
    {% block foot %}{% endblock %}
</body>
</html>

templates/create-account.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Create An Account{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-4 col-lg-offset-4">

            <div class="well">
                {{ form.non_field_errors }}
                <form action="" method="POST">{% csrf_token %}
                    <legend>Just a few questions for you:</legend>
                    <div class="form-group">
                        <label>Username? <small><em>Log in with this.</em></small></label>
                        {{ form.username|add_class:"form-control" }}
                        {{ form.username.errors }}
                    </div>
                    <div class="form-group">
                        <label>Password? <small><em>Make it real secure.</em></small></label>
                        {{ form.password1|add_class:"form-control" }}
                        {{ form.password1.errors }}
                    </div>
                    <div class="form-group">
                        <label>Retype Password? <small><em>Just in case.</em></small></label>
                        {{ form.password2|add_class:"form-control" }}
                        {{ form.password2.errors }}
                    </div>
                    <input type="submit" class="btn btn-success" value="Create that account!" />
                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/game.html
{% extends "base.html" %}
{% load custom_tags %}
{% block title %}Play that Game{% endblock %}

{% block head %}
<style>
.navbar {
    margin-bottom: 4px !important;
}
{% if request.user.col < 25 %}
    .board-row {
        float: right;
    }
{% endif %}
</style>
{% endblock %}

{% block goesinfoot %}
{% endblock %}

{% block body_class %}game{% endblock %}

{% block game_toolbar %}
<button type="button" class="btn navbar-btn btn-lg pull-right" data-bind="
    css: {
        'btn-success': clockSeconds() > 15,
        'btn-warning': clockSeconds() > 5 && clockSeconds() <= 15,
        'btn-danger': clockSeconds() <= 5 && clockSeconds() >= 0,
        'btn-primary': clockSeconds() < 0
    },
    text: clockDisplay
    "></button>

{% endblock %}

{% block content %}

<div class="container-fixed">
    <div class="row">
        <div class="col-md-3 sidebar">
            <h4>Minimap:</h4>
            <img class="minimap" src="{{ STATIC_URL }}images/minimap.png" alt="" />
            <h4>Heard in the last 10 seconds:</h4>
            <div class="well" style="height: 156px; overflow-y: scroll;">
                {% for announcement in announcements %}
                <p><strong>Announcer</strong>: {{ announcement.text }}</p>
                {% endfor %}


                <!-- ko foreach: otherPlayers -->
                    <!-- ko if: last_chat_message != '' -->
                    <p><strong data-bind="text: username"></strong>: <span data-bind="text: last_chat_message"></span></p>
                    <!-- /ko -->
                <!-- /ko -->

                <!-- ko if: $root.account() && $root.account().last_chat_message != '' -->
                <p><strong data-bind="text: $root.account().username"></strong>: <span data-bind="text: $root.account().last_chat_message"></span></p>
                <!-- /ko -->
            </div>
        </div>
        <div class="col-md-7">
            <div class="board-overlay"></div>
            <div class="board">
                {% for row in rows %}
                    <div class="board-row">
                        {% for square in row %}
                            <div class="square" style="
                                background-position: {{ square.get_css_offset_x }} {{ square.get_css_offset_y }}"

                                data-bind="
                                attr: {
                                    'data-col': {{ square.col }},
                                    'data-row': {{ square.row }},
                                    'data-terrain': '{{ square.get_terrain_type }}'
                                }
                                ">
                                {% if square.col == request.user.col and square.row == request.user.row %}
                                <div class="player-name">{{ request.user.username }} ({{ request.user.flags_gotten }}f,{{ request.user.enemies_tagged }}t)</div>
                                <div class="player {{ request.user.direction }} {{ request.user.team }}{% if request.user.has_flag %} flag{% endif %}">
                                    </div>
                                {% endif %}
                                <div class="other-player-name"></div>
                                <div class="other-player"></div>
                                <div class="arrow"></div>
                                <div class="other-arrow"></div>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
            <input class="form-control chat-entry" placeholder="Type chat messages here to be said during the next 10 seconds" type="text" data-bind="visible: clockSeconds() > 0, value: $root.currentChatMessage, valueUpdate: 'keyup'" maxlength="75" />

        </div>
        <div class="col-md-2 sidebar" style="padding-left: 30px">
            <!-- ko if: clockSeconds() > 0 -->
            <div class="btn-group-vertical" style="width: 100%" data-bind="foreach: actions">
                <button type="button" class="btn btn-primary btn-action" data-bind="
                    click: $root.chooseAction,
                    html: $root.getActionButtonContent(icon) + name,
                    attr: {
                        'data-action': which,
                        'data-seconds': seconds,
                        'data-stamina': stamina
                    }

                    "></button>
            </div>
            <h4><span data-bind="text: secondsRemaining"></span> Seconds To Fill</h4>

            <div class="actions-panel btn-group-vertical" data-bind="foreach: chosenActions">
                <button class="btn btn-block btn-sm btn-success" data-bind="
                    html: $root.getActionButtonContent(icon) + name,
                    click: $root.cancelAction
                    ">
                </button>
            </div>
            <h4>Stamina: <span data-bind="text: $root.staminaRemaining"></span></h4>
            <!-- /ko -->
        </div>
    </div>
</div>

{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load custom_tags %}
{% block title %}Home{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <div class="well">
                <img class="pull-right img-thumbnail" src="{{ STATIC_URL }}images/minimap.png" alt="" />
                <h1>Capture the Massively Multiplayer Online Flag</h1>
                <h2>A Real Time Turn Based game that happens in increments of 10 seconds.</h2>

                <div style="width: 420px;">
                    <a class="btn btn-primary btn-block btn-lg" href="{% url 'login' %}">Log In</a>
                    <a class="btn btn-success btn-block btn-lg" href="{% url 'create-account' %}">Create Account</a>
                </div>

                <h3>David S. Colgan, Ludum Dare 27</h3>
                <p><a href="https://twitter.com/davidscolgan/">Twitter: @davidscolgan</a></p>
                <p><a href="http://twitch.tv/dvcolgan/">Twitch.TV: dvcolgan</a></p>

                <p>I always wanted to be a red-shirted flag-stealing brunette man, who resolves all of his life in small 10-second time slices... -Sagehand</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/leaderboards.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Leaderboards{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>Leaderboards for Capture the Massively Multiplayer Online Flag!</h1>

            <h2>Team Stats</h2>
            <p>Here be the total flags captured and opponents tagged for each team.</p>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th class="danger">Red Tags</th>
                        <th class="danger">Red Flags</th>
                        <th class="active">Blue Tags</th>
                        <th class="active">Blue Flags</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="danger"><strong>{{ red_tags }}</strong></td>
                    <td class="danger"><strong>{{ red_flags }}</strong></td>
                    <td class="active"><strong>{{ blue_tags }}</strong></td>
                    <td class="active"><strong>{{ blue_flags }}</strong></td>
                </tr>
                </tbody>
            </table>

            <h2>Most Flags Captured</h2>
            <p>Here be the players who have captured the most flags while venturing into enemy territory.</p>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Username</th>
                        <th>Team</th>
                        <th>Flags</th>
                    </tr>
                </thead>
                <tbody>
                {% for player in top_flag_getters %}
                <tr class="{% if player.team == 'red' %}danger{% elif player.team == 'blue' %}active{% endif %}">
                    <td>{{ player.username }}</td>
                    <td>{{ player.get_team_display }}</td>
                    <td><strong>{{ player.flags_gotten }}</strong></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

            <h2>Most Opponents Tagged</h2>
            <p>Here be the players who have tagged the most opponents while guarding their team's flag.</p>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Username</th>
                        <th>Team</th>
                        <th>Tags</th>
                    </tr>
                </thead>
                <tbody>
                {% for player in top_taggers %}
                <tr class="{% if player.team == 'red' %}danger{% elif player.team == 'blue' %}active{% endif %}">
                    <td>{{ player.username }}</td>
                    <td>{{ player.get_team_display }}</td>
                    <td><strong>{{ player.enemies_tagged }}</strong></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>
{% endblock %}

templates/qunit-tests.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>QUnit Example</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/qunit-1.12.0.css">
</head>
<body>
<div id="qunit"></div>
<div id="qunit-fixture"></div>
<script src="{{ STATIC_URL }}js/qunit-1.12.0.js"></script>
<script src='{{ STATIC_URL }}js/jquery-2.0.1.min.js'></script>
<script src="{{ STATIC_URL }}js/colorpicker/colorpicker.min.js"></script>
<script src="{{ STATIC_URL }}js/jquery.cookie.js"></script>
<script src="{{ STATIC_URL }}js/knockout-2.3.0.js"></script>
<script src="{{ STATIC_URL }}js/spin.min.js"></script>
<script src="{{ STATIC_URL }}js/tests.js"></script>
</body>
</html>